homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirm/', views.confirm, name='confirm'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.TextField('name', max_length = 50, primary_key = True)
    status = models.TextField('status', max_length = 100)
    time = models.DateTimeField(auto_now_add = True, null = True)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput, required=True)
    # name = forms.CharField(widget=forms.TextInput(attrs={
    #     'class' : 'form-control',
    #     'placeholder' : "hey! what's your name?",
    #     'type' : 'text',
    #     'maxlength' : '50',
    #     'required' : True,
    #     'label' : '',
    # }))
    status = forms.CharField(widget=forms.TextInput, required=True)
    # status = forms.CharField(widget=forms.TextInput(attrs={
    #     'class' : 'form-control',
    #     'placeholder' : "how are you feeling today?",
    #     'type' : 'text',
    #     'maxlength' : '100',
    #     'required' : True,
    #     'label' : '',
    # }))
    class Meta:
        model = User
        fields = ['name', 'status']
        widgets = {'model': forms.TextInput()}
        type = 'text'
        required = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import User
from .forms import UserForm

#Create your views here.
# def index(request):
# 	usernya = User.objects.all().values()
# 	if (request.method == 'POST'):
# 		form = UserForm(request.POST)
# 		if (form.is_valid()):
# 			return render(request, 'confirm.html', {'usernya': usernya, 'form':form})
# 			# form.save()
# 			# return redirect('/')
# 	else:
# 		form = UserForm()
# 	return render(request, 'index.html', {'usernya': usernya, 'form':form})

def index(request):
	if request.method == "POST":
		form = UserForm(request.POST)
		if (form.is_valid()):
			new_name = form.cleaned_data['name']
			new_status = form.cleaned_data['status']
			response = {'name':new_name, 'status':new_status}
			return render(request, 'confirm.html', response)
	else:
		form = UserForm()
	usernya = User.objects.all()
	response = {'usernya' : usernya}
	return render(request, 'index.html', response)


def confirm(request):
	if request.method == "POST":
		form = UserForm(request.POST)
		if (form.is_valid()):
			new_user = User()
			new_user.name = form.cleaned_data['name']
			new_user.status = form.cleaned_data['status']
			new_user.save()
			return redirect('homepage:index')

	else:
		form = UserForm()
	return render(request,'confirm.html')

homepage/templates/confirm.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">

    <style>
        html, body {
          width: 100%;
          height: 100%;
          margin: 0;
          padding: 0;
          overflow-x: hidden;
        }
    </style>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <title>h e l l o ! | z a h r a </title>
  </head>
<body>
    <div class="row five">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h1 class="info">are you sure you want to submit this?</h1>
            <form action="{% url 'homepage:confirm' %}" method="POST">
                {% csrf_token %}
                <div class="row six">
                    <h3 style="font-family: Raleway; color: yellow; padding-left: 30px;">   your name</h3>
                    <input type="text" class="form-control" id="name" name="name" style = "color: #F7ECDF" maxlength="50" readonly value="{{ name }}">
                    <h3 style="font-family: Raleway; color: yellow; padding-left: 30px;">  you are feeling</h3>
                    <input type="text" class="form-control" id="status" name="status" style = "color: #F7ECDF" maxlength="100" readonly value="{{ status }}">
                </div>
                <div class="row seven">
                    <input type="submit" name="confirm" value="Confirm" id="confirm">
                    <a href="{% url 'homepage:index' %}" id="cancel" name="cancel">Cancel</a>        
                </div>
            </form> 
        </div>
        <div class="col-md-3"></div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>        
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://fonts.googleapis.com/css?family=Yeseva+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <title>h e l l o | z a h r a</title>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p id="formTitle">hi! what's poppin?</p>
                <form action="/" method = 'POST' class="topform">
                    {% csrf_token %} 
                    <div class="form-row">
                        <div class="form-group col-sm-12">  
                            <input type="text" class="form-control" id="name" name="name" maxlength="50" placeholder="hey! what's your name?" required>
                            <br>
                            <input type="text" class="form-control" id="status" name="status" maxlength="100" placeholder="how are you feeling today?" required>
                            <!-- <div class="textfield" id= "textBox">
                                    {% for fields in form %}
                                    {{ fields }}
                                    {% endfor %}
                            </div>             
                             -->
                        </div>
                    </div>
                    <div class="form-row">
                        <input type="submit" class="btn btn-add btn-warning" value="Submit" id="submit">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="text-center">
                    <br><br><br>
                        <p id="namanya">user list</p>
                        <button id="change-color" onclick="change()">change color</button>
                        <br>
                        <!-- <p>  -->
                            <div id="resp" style=" overflow-y: scroll;">
                                <!-- <table> -->
                                        {% for usernya in usernya %}
                                        <div id="response">
                                            <h1 class="thename" style="color:white ;">{{ usernya.name }}</h1>
                                            <h1 class="thestatus" style="color: white;">{{ usernya.status }}</h1>
                                            <p class="statustime" style="color: white">{{ usernya.time }}</p>
                                            </div> 
                                        {% endfor %}
                                    <!-- </table>   -->
                                </div>
                </div>
            </div>
        </div>
    </div>
</body>
    <script>
        function change() {
          var time = document.getElementsByClassName("statustime");
          var name = document.getElementsByClassName("thename");
          var status = document.getElementsByClassName("thestatus");
          var i;
          for(i = 0; i < time.length; i++) {
            time[i].style.color = "rgba(33,37,41,1)";
          }   
          for(i = 0; i < name.length; i++) {
            name[i].style.color = "rgba(33,37,41,1)";
          }
          for(i = 0; i < status.length; i++) {
            status[i].style.color = "rgba(33,37,41,1)";
          }      
        }
      </script>
    


</html>